apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
 name: rc-ceph-7-1-z10-respin-stage-release-20260831-0522
 namespace: ceph-tenant
 labels:
   release.appstudio.openshift.io/automated: "false"
   release.appstudio.openshift.io/author: rkamath
spec:
  releasePlan: ceph-7-1-stage-rp
  snapshot: ceph-7-1-z10-respin-rc-snapshot-20260831-0522
  data:
    releaseNotes:
      type: RHBA
    references: |
      - https://docs.redhat.com/en/documentation/red_hat_ceph_storage/