apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-8-1-z8-respin-rc-snapshot-20261007-0025
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-8-1
  components:
    - name: rhceph-container-8-1
      containerImage: quay.io/rhceph-ci/rhceph@sha256:8d1b38cc542a787b517c11e03b9464a83bf87416e5b23b33502d8f074d99c6ca
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container
          revision: 569d9de5659a9544deb1515af2e4c9955c70a794