apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-9-0-z1-respin-rc-snapshot-5
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-9-0
  components:
    - name: rhceph-container-9-0
      containerImage: quay.io/rhceph-ci/rhceph@sha256:3bac413c438dba4872d67772161f2bac354b6de33a1ecd0f15828ecc2dfd4439
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: 076fe79af2e6581df82749640869e35f6d21faf2
