apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-9-0-z1-respin-rc-snapshot-6
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-9-0
  components:
    - name: rhceph-container-9-0
      containerImage: quay.io/rhceph-ci/rhceph@sha256:68177a0eed65d949f5080ccf63e8b26e6448264dcdacb3c9e5f70aa2d662bcea
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: 9fd1ad0a835445b4c8546cc221ec14a796dfb68b
