apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- overlays/qe-build-email-7-1
- overlays/qe-build-email-8-1
- overlays/qe-build-email-9-0
- overlays/qe-build-email-9-1
- overlays/qe-build-email-9-2
- overlays/qe-jenkins-integration-9-2
