apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base # Path to base component

patches:
  - path: ceph-nvmeof-override.yaml # Path to override file
    target:
      kind: Component
