apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-9-0-z2-rc-4-snapshot
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-9-0
  components:
    - name: keepalived-9-0
      containerImage: quay.io/rhceph-ci/keepalived@sha256:76b7c9669f8fadee57c49a3e9a19f238027e4b8dd8d2f9f43997e7ddcaddd851
      source:
        git:
          url: https://github.com/ibmstorage/keepalived.git
          revision: f766cafeab11b574dfaf184dce97165834623ce2
    - name: alloy-9-0
      containerImage: quay.io/rhceph-ci/alloy@sha256:3b1c231c8a1de28c7bcda810c7b15c4685176ce799d68998aee16c40dcb44371
      source:
        git:
          url: https://github.com/ibmstorage/alloy-container.git
          revision: 44e93398894700aa09ff5863e910ec2270e90987
    - name: rhceph-container-9-0
      containerImage: quay.io/rhceph-ci/rhceph@sha256:d173a744d12b082bdd59e3250c31cef525c02fa5cb3488f41a2ae9396cab5dfb
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: bd82fac841c716fb8dd153e3ccbf3d28858f8ab1
    - name: snmp-notifier-9-0
      containerImage: quay.io/rhceph-ci/snmp-notifier@sha256:9beb6a833b2d5ca77211022cf1cd0e53a92b4af67903a5c2b030d9615643b181
      source:
        git:
          url: https://github.com/ibmstorage/snmp-notifier-container.git
          revision: fb2a8aa991079cdf7fffb062645447db71aed521
    - name: grafana-9-0
      containerImage: quay.io/rhceph-ci/grafana@sha256:0f1a905421a7cea6f2663e0803115fa611053705ae9894d0316db36711eea5e2
      source:
        git:
          url: https://github.com/ibmstorage/grafana-container.git
          revision: b3ede66e01a1f391f6331032ecd4663a015089b3
    - name: haproxy-9-0
      containerImage: quay.io/rhceph-ci/haproxy@sha256:40381e3145fcced24195df79158d5ccbda58a3ab7f62850c0a5b1c1712829407
      source:
        git:
          url: https://github.com/ibmstorage/haproxy.git
          revision: 30673f2efd580e8491abfa2b3ae31653d3d760c9
    - name: oauth2-proxy-9-0
      containerImage: quay.io/rhceph-ci/oauth2-proxy@sha256:7c8fbbdcaecad706ca8a995b4e90cc8a83c06f39a9077550752a36bfb0c44888
      source:
        git:
          url: https://github.com/ibmstorage/oauth2-proxy-container.git
          revision: f68da9d0f2d3fb3acc55834c505cebd299cb600e
