apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-8-1-z9-rc-snapshot-20261001-1012
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-8-1
  components:
    - name: rhceph-container-8-1
      containerImage: quay.io/rhceph-ci/rhceph@sha256:17ce36c87190f8d82147274a45a1e9e37f0b1fdd7196c34e27f50716458bfc5e
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: e7998130a5805a65294482dec5d59ee300a29ab9
    - name: snmp-notifier-8-1
      containerImage: quay.io/rhceph-ci/snmp-notifier@sha256:1811847b656def397d079790cc0cc5ad16be8d8f8c50c045e946424291246fe9
      source:
        git:
          url: https://github.com/ibmstorage/snmp-notifier-container.git
          revision: 9164cb1b6eadaccc52c1cb578b224e0d4ef79a7f
    - name: haproxy-8-1
      containerImage: quay.io/rhceph-ci/haproxy@sha256:c50d19c04ecd8c3a59280707a9e9ed378fac96f48412d188dba9e9f96153cf81
      source:
        git:
          url: https://github.com/ibmstorage/haproxy.git
          revision: 21ccd82cc10998390f2d77ae4ee72e24703fa6ef
    - name: grafana-8-1
      containerImage: quay.io/rhceph-ci/grafana@sha256:131d34984ded6e4fd769084afc635bf480f9b15016a8ae2629c832cc9da7e323
      source:
        git:
          url: https://github.com/ibmstorage/grafana-container.git
          revision: 575ad466b602b9c101e9820b55a66c57c9921044
    - name: keepalived-8-1
      containerImage: quay.io/rhceph-ci/keepalived@sha256:b8a8825fe05f28f5b0326b7b7dca20b305da3a24def8a94b2a3b17b0747f8087
      source:
        git:
          url: https://github.com/ibmstorage/keepalived.git
          revision: 7b52fdfcb5a3498643bf6997fcd099322a1e66ae
    - name: promtail-8-1
      containerImage: quay.io/rhceph-ci/promtail@sha256:8fa9f81ff7238ba2bd6c36575ecd0fa2471d4061a37a592e74164211631f618c
      source:
        git:
          url: https://github.com/ibmstorage/promtail.git
          revision: e61a6a770b0ec38f8397d050275302868280c89a
    - name: oauth2-proxy-8-1
      containerImage: quay.io/rhceph-ci/oauth2-proxy@sha256:729bfdfd541aa618252bbd4f1b1c917b083594d4f276854f189beb644781d647
      source:
        git:
          url: https://github.com/ibmstorage/oauth2-proxy-container.git
          revision: bd83779648c831febfcaf670074ec9eb297a6013