apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
 name: rc-ceph-9-1-z1-respin-stage-release-20260817-1839
 namespace: ceph-tenant
 labels:
   release.appstudio.openshift.io/automated: "false"
   release.appstudio.openshift.io/author: rkamath
spec:
  releasePlan: ceph-9-1-stage-rp
  snapshot: ceph-9-1-z1-respin-rc-snapshot-20260817-1839
  data:
    releaseNotes:
      type: RHBA
    references: |
      - https://docs.redhat.com/en/documentation/red_hat_ceph_storage/