apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-9-0-z3-rc-1-snapshot
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-9-0
  components:
    - name: keepalived-9-0
      containerImage: quay.io/rhceph-ci/keepalived@sha256:3e528883f994a1df82dde20df0a7f6389ce401cb3e57cb1df2c8c0e17ab50eea
      source:
        git:
          url: https://github.com/ibmstorage/keepalived.git
          revision: dedee3886387167d2911d7dcf1aa70f689a1d482
    - name: alloy-9-0
      containerImage: quay.io/rhceph-ci/alloy@sha256:6f1e365b744b05da39eb81f9eb3ddd3ae0b0d703fdfb2782d589347ccce4968b
      source:
        git:
          url: https://github.com/ibmstorage/alloy-container.git
          revision: 56ed37040c32f79aa016a7972ecf916fa09b2504
    - name: rhceph-container-9-0
      containerImage: quay.io/rhceph-ci/rhceph@sha256:b323a17a6f61b08f4e4337f4818f86d308a2c8c067213e745d6e62a753a16bda
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: 7b373edce130517b0d752ea020dde89f8cbd0733
    - name: snmp-notifier-9-0
      containerImage: quay.io/rhceph-ci/snmp-notifier@sha256:9ce73f34932e59c07bd6e908647ba36c8ee6745ed70333128e410d8b5210ea72
      source:
        git:
          url: https://github.com/ibmstorage/snmp-notifier-container.git
          revision: b90e04a65758d6918dcdbd47f17b55904cc6031e
    - name: grafana-9-0
      containerImage: quay.io/rhceph-ci/grafana@sha256:b07fd497f98d1f8210a73766af1510dd863915392be3a2dd9190a4379afa9db4
      source:
        git:
          url: https://github.com/ibmstorage/grafana-container.git
          revision: 6105b614b24f7de75e24f029077f79e0aecb9d32
    - name: haproxy-9-0
      containerImage: quay.io/rhceph-ci/haproxy@sha256:d7bffb4dbfacc4d27c8ec2032d9cb55c4dddf87cb8883f3037a3afeabb0d8c36
      source:
        git:
          url: https://github.com/ibmstorage/haproxy.git
          revision: 3a824996b3e31a753fe55177c9211c5c7b345c90
    - name: oauth2-proxy-9-0
      containerImage: quay.io/rhceph-ci/oauth2-proxy@sha256:95e9659112580c95d590737975f3cc7d3314ccb526cb189720040ce0897a6958
      source:
        git:
          url: https://github.com/ibmstorage/oauth2-proxy-container.git
          revision: 08ce63c4e3ed5e464517eaa10a48e0814dde6e34
