apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-9-0-0-rc10
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-9-0
  components:
    - name: keepalived-9-0
      containerImage: quay.io/rhceph-ci/keepalived@sha256:11a8d7e5cc5250e9893f1f39296ade12dece8f106026ab871843cac9b8d93614
      source:
        git:
          url: https://github.com/ibmstorage/keepalived.git
          revision: 1e5a03a6c693cae1926905486c2bd2951678e78f
    - name: alloy-9-0
      containerImage: quay.io/rhceph-ci/alloy@sha256:98bcfac8394a572723d3bd0b4a2017b3fdd8f5d74191eea50d57d61233b62666
      source:
        git:
          url: https://github.com/ibmstorage/alloy-container.git
          revision: cfbd9ca13187be37b7c6ca831bb5290016e7db81
    - name: rhceph-container-9-0
      containerImage: quay.io/rhceph-ci/rhceph@sha256:13a182ad46f11a4a38b5e530f92c6549f5e8cc736521bd01261f977a3787e218
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: bd6c57fbe41cb2b3220405e2f9911516ed24fad5
    - name: snmp-notifier-9-0
      containerImage: quay.io/rhceph-ci/snmp-notifier@sha256:0c95b1c4ac9b517317a16338c2b443f279edc857469bef61053fe57f4e5398b4
      source:
        git:
          url: https://github.com/ibmstorage/snmp-notifier-container.git
          revision: a6e08196623c8eddf51538ef55b8a81dd040162a
    - name: grafana-9-0
      containerImage: quay.io/rhceph-ci/grafana@sha256:24dfc8f83b074d5b015a211464aaa7efa51f7a7519badee40bf50170e1906dae
      source:
        git:
          url: https://github.com/ibmstorage/grafana-container.git
          revision: 368117818ad0f585b3efa21864a28688a22d1f14
    - name: haproxy-9-0
      containerImage: quay.io/rhceph-ci/haproxy@sha256:188cc53889b7ffb6e5f8f3e7099bb21bdfc7c0b89e42fe3cead15d03368800cd
      source:
        git:
          url: https://github.com/ibmstorage/haproxy.git
          revision: dbb2caf1ce2c59a5c479b12bc74a7ce467563aee
