kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: my-jenkins-trigger
spec:
  params:
    - name: JENKINS_HOST_URL
      type: string
    - name: JOB_NAME
      type: string
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      type: string
  tasks:
    - name: extract-build-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test-metadata/0.3/test-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: trigger-jenkins-job
      taskRef:
        resolver: "git"
        params:
        - name: url
          value: https://github.com/konflux-ci/tekton-integration-catalog.git
        - name: revision
          value: main
        - name: pathInRepo
          value: tasks/triggers/jenkins/0.1/trigger-jenkins-job.yaml
      params:
        - name: JENKINS_HOST_URL
          value: $(params.JENKINS_HOST_URL)
        - name: JOB_NAME
          value: $(params.JOB_NAME)
        - name: JENKINS_SECRETS
          value: rkamath-jenkins-api
        - name: JOB_PARAMS
          value:
          - TEST_KONFLUX_STRING_PARAM=$(params.SNAPSHOT)
          - TEST_SNAPSHOT_META=$(tasks.extract-build-metadata.results)
