apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-7-1z10-rc-2-snapshot
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-7-1
  components:
    - name: rhceph-container-7-1
      containerImage: quay.io/rhceph-ci/rhceph@sha256:a8384a1a9b6ed0465877ff3b366a8ce2bcb67d6405c01883be75411bbee3c4b1
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: 422a0e222f9ef899ad0f00bff5858f890db537d6
    - name: snmp-notifier-7-1
      containerImage: quay.io/rhceph-ci/snmp-notifier@sha256:bc53c9344364b772e95eda97d14ff0b18521f5e1776556915ded41f6c0342297
      source:
        git:
          url: https://github.com/ibmstorage/snmp-notifier-container.git
          revision: 0ede6b42b301538009df5364392c3e06a0338088
    - name: keepalived-7-1
      containerImage: quay.io/rhceph-ci/keepalived@sha256:231798ca52d249e3bbcd0ae34ff364a8798325fbac3c9a1c678c7f884add9bbf
      source:
        git:
          url: https://github.com/ibmstorage/keepalived.git
          revision: 68049300dd2bfa9e92c344497fc50be952a677d7
    - name: grafana-7-1
      containerImage: quay.io/rhceph-ci/grafana@sha256:c0f003f063aec54e45d08b73c9ecd90938d878b3294bf62fb9edeeacfb607be2
      source:
        git:
          url: https://github.com/ibmstorage/grafana-container.git
          revision: a9636b7a4b8cb2369916f73294625a5a1a6ceb86
    - name: haproxy-7-1
      containerImage: quay.io/rhceph-ci/haproxy@sha256:ce155acadabc940162f97cb476c0d1c4e07c02217c595427a58701bc7285efd1
      source:
        git:
          url: https://github.com/ibmstorage/haproxy.git
          revision: c69041bff8ea1132cfb26c5bbec6eddf5403685a
    - name: promtail-7-1
      containerImage: quay.io/rhceph-ci/promtail@sha256:2c1e737fe2caa6476144ebf21be4c555e5de7e2407bd23354d94cd33002e123b
      source:
        git:
          url: https://github.com/ibmstorage/promtail.git
          revision: acb3e93ca3b9b7b42f5fb81b0ffb5f034ba63cfe
