apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-7-1-z9-respin-3-rc1-snapshot
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-7-1
  components:
    - name: rhceph-container-7-1
      containerImage:
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: 
