apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: <component-name>
  namespace: ceph-tenant
  annotations:
    #if onboarding a new component in a new repo uncomment this line
    #build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
spec:
  application: ceph
  componentName: <component-name>
  source:
    git:
      url: https://github.com/konflux-ci/testrepo.git
      revision: main
      context: ./
      dockerfileUrl: Containerfile
  containerImage: <oci-repository-to-push-image-to>
