apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
 name: ceph-9-1-prod-release
 namespace: ceph-tenant
 labels:
   release.appstudio.openshift.io/automated: "false"
   release.appstudio.openshift.io/author: syeshwan
spec:
  releasePlan: ceph-9-1-prod-rp
  snapshot: ceph-9-1-rc-snapshot-20260619-0658
  data:
    releaseNotes:
      type: RHBA
    references: |
      - https://docs.redhat.com/en/documentation/red_hat_ceph_storage/