apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: '-9-0' # Add a suffix to all resource names in the application for uniqueness
resources:
  - ../base
  - ../base/keepalived
  - ../base/haproxy
  - ../base/snmp-notifier
  - ../base/promtail
  - ../base/grafana
  - ../base/rhceph
  - ../base/rhceph-container
  - ../base/alloy

patches:
  - target:
      kind: Application
    path: application-patch.yaml
  - target:
      kind: Component
    path: component-patch.yaml
