apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ceph-tenant

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: qe-build-email-8-1
    - op: replace
      path: /spec/application
      value: ceph-8-1
    - op: replace
      path: /spec/contexts/0/name
      value: component_rhceph-container-8-1
  target:
    kind: IntegrationTestScenario
