apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-8-1-z6-snapshot-2
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-8-1
  components:
    - name: rhceph-container-8-1
      containerImage: quay.io/rhceph-ci/rhceph@sha256:85d88fd7e753698e1c82e97150c35790d2c545422f399c531bb55a97f41961a7
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: 4781d637466059d9ae5765765d4c298216c1ef72
    - name: grafana-8-1
      containerImage: quay.io/rhceph-ci/grafana@sha256:94372517ef3ded51d6dc84af022d78bcae06087bd46e9895bb31f63262e1371b
      source:
        git:
          url: https://github.com/ibmstorage/grafana-container.git
          revision: 769d6d3bbfbfba5c092f3f3b7eb009b1ce7c2d76
    - name: haproxy-8-1
      containerImage: quay.io/rhceph-ci/haproxy@sha256:7d6b6e3bdbcc9315e8b79be75467316a975b547c78e0f210408b6abd20d8d938
      source:
        git:
          url: https://github.com/ibmstorage/haproxy.git
          revision: ac32b43ce75af24487f32867f96a3536becf936d
    - name: keepalived-8-1
      containerImage: quay.io/rhceph-ci/keepalived@sha256:955722d8c282523d6ac8b2044059ab891301289907b494572128b9e1047c15bd
      source:
        git:
          url: https://github.com/ibmstorage/keepalived.git
          revision: e1b4c0a2017bd5d589acfeb02914b0e6b054b26d
    - name: promtail-8-1
      containerImage: quay.io/rhceph-ci/promtail@sha256:0810d08859d93cd634729f0b8131952837d010d0d8b3fd6d22fb6e1005336d4d
      source:
        git:
          url: https://github.com/ibmstorage/promtail.git
          revision: 5e26e74b18088a909a9ca991cf9d0caecfb7db92
    - name: snmp-notifier-8-1
      containerImage: quay.io/rhceph-ci/snmp-notifier@sha256:ae68e10f6afd99be8a9ea014a8cf7a49414cb68b95920e90af8a76eb0f78a20f
      source:
        git:
          url: https://github.com/ibmstorage/snmp-notifier-container.git
          revision: f7d293e02b03d7640fff4413831bac43c5aa42ee
    - name: oauth2-proxy-8-1
      containerImage: quay.io/rhceph-ci/oauth2-proxy@sha256:8e39ea09c335b4c40230615e8a92629592eb0442823ebf32439d6ecc2e2c6f12
      source:
        git:
          url: https://github.com/ibmstorage/oauth2-proxy-container.git
          revision: feb93e971fd020e1e954ab11b4b1b7499f12c6a8