apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-8-1-z8-respin-rc-snapshot-20260814-0302
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-8-1
  components:
    - name: rhceph-container-8-1
      containerImage: quay.io/rhceph-ci/rhceph@sha256:da0c5410d17f274653eb0bc5e6107e9171f1f16b52e95619f7b489776ab1f0de
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container
          revision: e75d57da0fae2ee344e86bc426b489e0170a248f