apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#nameSuffix: '-8.1' # Add a suffix to all resource names in the application for uniqueness
resources:
  - ../base
  - ../base/ceph-nvmeof
  - ../base/ceph-nvmeof-cli

patches:
  - target:
      kind: Application
    path: application-patch.yaml
  - target:
      kind: Component
    path: component-patch.yaml
