apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ceph-7-1-z9-respin-rc-snapshot_2026-June-04_0130
  namespace: ceph-tenant
  labels:
    test.appstudio.openshift.io/type: override
spec:
  application: ceph-7-1
  components:
    - name: rhceph-container-7-1
      containerImage: quay.io/rhceph-ci/rhceph@sha256:4f25889954300943e49ecb04e7afc9201f4ddea8d7ce47918a3833a7920151fc
      source:
        git:
          url: https://github.com/ibmstorage/rhceph-container.git
          revision: a98d3b181a341ac673bd3010b4d4f873d9b4ab02